"""Prepare a separate SurrealDB 2.x restore script without editing the raw backup."""

import argparse
import os
from pathlib import Path

# Relation endpoints and array child fields may be generated by DEFINE TABLE/
# parent fields. Match the current exporter, which uses OVERWRITE for all fields.
# Process only schema blocks; preserve table data verbatim.


def prepare(source: Path, destination: Path):
    if source.resolve() == destination.resolve() or destination.exists():
        raise ValueError("The restore copy must be a new, separate file")
    text = source.read_text()
    schema = False
    count = 0
    lines = []
    for line in text.splitlines(keepends=True):
        # The 2.x CLI may append its export completion logger to stdout.
        # Drop only that exact out-of-band logger line, retaining the raw backup.
        if line.startswith("\x1b[") and "surreal::cli::export" in line:
            continue
        if line.startswith("-- TABLE: "):
            schema = True
        elif line.startswith("-- TABLE DATA: "):
            schema = False
        if (
            schema
            and line.startswith("DEFINE FIELD ")
            and not line.startswith(
                ("DEFINE FIELD OVERWRITE ", "DEFINE FIELD IF NOT EXISTS ")
            )
        ):
            line = line.replace("DEFINE FIELD ", "DEFINE FIELD OVERWRITE ", 1)
            count += 1
        lines.append(line)
    text = "".join(lines)
    with destination.open("x") as stream:
        os.chmod(destination, 0o600)
        stream.write(text)
    return count


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("destination", type=Path)
    args = parser.parse_args()
    print(
        f"Prepared restore copy; {prepare(args.source, args.destination)} schema fields made idempotent"
    )
